/*
 * NTI.c
 *
 * Created: 3/2/2023 1:16:06 AM
 * Author : Dell
 */ 


//#include "APP/TIMERAPPLICATION1/TIMERAPPLICATION1.h"
//#include "APP/STEPPERAPPLICATION/STEPPERAPPLICATION.h"
//#include "APP/SEVENSEGMENTAPPLICATION/SEVENSEGMENTAPPLICATION.h"
//#include "APP/PWMAPPLICATION1/PWMAPPLICATION1.h"
//#include "APP/LCDAPPLICATION/LCDAPPLICATION.h"
//#include "APP/INTERRUPTAPPLICATION1/INTERRUPTAPPLICATION1.h"
//#include "APP/HOMESECURITYAPPLICATION/BUZZERAPPLICATION.h"
//#include "APP/ADCAPPLICATION1/ADCAPPLICATION1.h"
//#include "APP/ICUAPPLICATION1/ICUAPPLICATION1.h"
#include "APP/ICUAPPLICATION2/ICUAPPLICATION2.h"
int main(void)
{
    APP_INIT();
    while (1) 
    {
	APP_RUN();
    }
}

